server:
  port: 8020

spring:
  security:
    user:
      name: user
      password: 1234

  mvc:
    hiddenmethod:
      filter:
        enabled: true

threads:
  virtual:
    enabled: true

thymeleaf:
  cache: falss

datasource:
  url: jdbc:h2:./sb_dev;MODE=MySQL
  driverClassName: org.h2.Driver
  username: sa
  password:

jpa:
  hibernate:
    ddl-auto: update